import sys


headers = """
#pragma once

#include <stdint.h>  // for uint8_t

#define M {size}
#define N {size}
#define K {size}
"""

decl = """
void {name}(uint8_t *restrict A, uint8_t *restrict B, uint8_t *restrict C);"""


# name: Naive, Block, or Pack
def generate_code(size, name):
    size = int(size)

    code = "/* Autogenerated file. Do not edit manually. */\n"
    code += headers.format(size=2**size, name=name)
    if name == "Naive":
        code += decl.format(name=name)
    else:
        for mc in range(0, size + 1):
            for nc in range(0, size + 1):
                for kc in range(0, size + 1):
                    code += decl.format(name=f"{name}_{2**mc}_{2**nc}_{2**kc}")
    return code


if __name__ == "__main__":
    size, name = sys.argv[1:3]
    print(generate_code(size, name))
