# Compiler settings
CC = clang
CFLAGS = -Wall -Wpedantic -std=gnu99 -fopenmp

# MORE_CFLAGS = -O1 -g -fsanitize=address
MORE_CFLAGS = -O3

LDFLAGS = -L. -lmatmul

# Archiver settings
AR = ar
ARFLAGS = rcs


# Matrix sizes
N_VALUE = 2048
M_VALUE = 2048
K_VALUE = 2048

# Possible tiling values for nc, kc, mc
NC_VALUES := 1 2 4 8 16 32 64 128 256 512 1024 2048
KC_VALUES := $(NC_VALUES)
MC_VALUES := $(NC_VALUES)

# Generate all possible BLIS implementations
BLIS_SRCS := $(foreach nc,$(NC_VALUES),$(foreach kc,$(KC_VALUES),$(foreach mc,$(MC_VALUES),Blis_$(nc)_$(kc)_$(mc).c)))
# Generate all possible GEMM implementations
GEMM_SRCS := $(foreach nc,$(NC_VALUES),$(foreach kc,$(KC_VALUES),$(foreach mc,$(MC_VALUES),Gemm_$(nc)_$(kc)_$(mc).c)))

# Common Source files
COMMON_SRCS = Bench.c Matmul.c

# Header files
HEADERS = Bench.h Matmul.h Blis.h Gemm.h

# Object files
OBJS = $(COMMON_SRCS:.c=.o) $(BLIS_SRCS:.c=.o) $(GEMM_SRCS:.c=.o)

# Executable files
EXECS = naive_run naive_bench blis_run blis_bench gemm_run morello_run morello_bench # blis_autotune gemm_autotune


all: $(EXECS)

$(EXECS): %: %.o libmatmul.a $(HEADERS)
	$(CC) $(CFLAGS) $(MORE_CFLAGS) -o $@ $< libmatmul.a $(LDFLAGS)

libmatmul.a: $(OBJS) $(HEADERS) $(BLIS_SRCS) $(GEMM_SRCS)
	$(AR) $(ARFLAGS) $@ $(OBJS)

Blis.h:
	@echo "/* Autogenerated header. Do not edit manually. */" > $@
	@echo "#pragma once" >> $@
	@echo "#include <stdint.h>  // for uint8_t" >> $@
	@echo "#define N $(N_VALUE)" >> $@
	@echo "#define M $(M_VALUE)" >> $@
	@echo "#define K $(K_VALUE)" >> $@
	@$(foreach nc,$(NC_VALUES),$(foreach kc,$(KC_VALUES),$(foreach mc,$(MC_VALUES),echo "void Blis_$(nc)_$(kc)_$(mc)(uint8_t *A, uint8_t *B, uint8_t *restrict C);" >> $@;)))

$(BLIS_SRCS): Blis.c.in
	@echo "/* Autogenerated file. Do not edit manually. */" > $@
	@sed -e 's/@NC_VALUE@/$(word 2,$(subst _, ,$*))/' \
	     -e 's/@KC_VALUE@/$(word 3,$(subst _, ,$*))/' \
	     -e 's/@MC_VALUE@/$(word 4,$(subst _, ,$*))/' $< >> $@

Blis_%_%.o: Blis_%_%.c Blis.h
	$(CC) $(CFLAGS) $(MORE_CFLAGS) -c $< -o $@

Gemm.h:
	@echo "/* Autogenerated header. Do not edit manually. */" > $@
	@echo "#pragma once" >> $@
	@echo "#include <stdint.h>  // for uint8_t" >> $@
	@echo "#define N $(N_VALUE)" >> $@
	@echo "#define M $(M_VALUE)" >> $@
	@echo "#define K $(K_VALUE)" >> $@
	@$(foreach nc,$(NC_VALUES),$(foreach kc,$(KC_VALUES),$(foreach mc,$(MC_VALUES),echo "void Gemm_$(nc)_$(kc)_$(mc)(uint8_t *A, uint8_t *B, uint8_t *restrict C);" >> $@;)))

$(GEMM_SRCS): Gemm.c.in
	@echo "/* Autogenerated file. Do not edit manually. */" > $@
	@sed -e 's/@NC_VALUE@/$(word 2,$(subst _, ,$*))/' \
	     -e 's/@KC_VALUE@/$(word 3,$(subst _, ,$*))/' \
	     -e 's/@MC_VALUE@/$(word 4,$(subst _, ,$*))/' $< >> $@

Gemm_%_%.o: Gemm_%_%.c Gemm.h
	$(CC) $(CFLAGS) $(MORE_CFLAGS) -c $< -o $@

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) $(MORE_CFLAGS) -c $< -o $@

check: naive_run blis_run gemm_run morello_run
	./naive_run
	./blis_run
	./gemm_run
	./morello_run
	diff -s --brief naive.txt blis.txt
	diff -s --brief naive.txt gemm.txt
	diff -s --brief naive.txt morello.txt

clean:
	rm -f *.o $(EXECS) libmatmul.a $(BLIS_SRCS) Blis.h $(GEMM_SRCS) Gemm.h
