name: C

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-20.04
          - ubuntu-22.04
        size:
          - 1 # 2^1 = 2
          - 2 # 2^2 = 4
          - 3 # 2^3 = 8
          - 4 # 2^4 = 16
          - 5 # 2^5 = 32
          - 6 # 2^6 = 64
          - 7 # 2^7 = 128
          - 8 # 2^8 = 256
          - 9 # 2^9 = 512
          - 10 # 2^10 = 1024
          - 11 # 2^11 = 2048
          - 12 # 2^12 = 4096
    steps:
      - uses: actions/checkout@v3

      - run: make test SIZE='${{ matrix.size }}'
